### ISSUE TITLE
Unexpected behavior with Ember.ArrayProxy

### ISSUE THREAD

**Issue by mwpastore** [kellyselden/ember-macro-helpers#109]
The `computed` macro does not play well with the proxied array properties of Ember.ArrayProxy. For example:

```javascript
foo: computed('[]', (bar) => {
  // `bar' is always undefined
})
```

Ideally, the first argument to the callback in the above example would resolve to the `content` property of the ArrayProxy, or even better, the ArrayProxy object itself. Unfortunately, it's `undefined` (actually, I think `@each` gives you undefined, `[]` gives you an error about calling Ember.get with an empty string). The workaround is to do this:

```javascript
foo: computed('content.[]', (bar) => {
  // `bar' is the content array
})
```

So maybe we can consider this a "nice to have" for the future. Here's a [Twiddle](https://ember-twiddle.com/7e78179e8ba8d15f10570cf9124eacbf) that demonstrates the behavior. Thank you!

**Comment by mwpastore** [comment]
Interestingly, in formulations like this:

```javascript
foo: computed('bar.[]', (bar) => {
})
```

Where `bar` is an Ember.ArrayProxy, the first argument to the callback is the ArrayProxy object. The the problem only manifests when you have a local/internal computed property dependent on `[]` or `@each`.

**Comment by kellyselden** [comment]
You're problem is difficult for me to understand. Are you saying that you are extending the Ember.ArrayProxy? Are you doing this?

```js
export default Ember.ArrayProxy.extend({
  foo: computed('[]', (bar) => {
    // `bar' is always undefined
  })
});
```

**Comment by mwpastore** [comment]
Yes, that's right. Sorry for not making that clearer.

**Comment by mwpastore** [comment]
@kellyselden Thoughts on this and #110?
