### ISSUE TITLE
Computed properties not triggering re-render

### ISSUE THREAD

**Issue by DuBistKomisch** [kellyselden/ember-macro-helpers#159]
Seems like the change in https://github.com/kellyselden/ember-macro-helpers/pull/142 causes no re-renders in my app at all after upgrading to 0.16.3. This happens on ember 2.13 and 2.16 at least. Everything renders fine on load and after refreshing, but for example created items don't appear in  `{{#each}}` loops bound to `array.filterBy`'d arrays.

Here's the relevant parts of my code, I may be doing something wrong but it was working fine on 0.16.0: https://github.com/DuBistKomisch/nou2ube/commit/d6322704cf6784bba79c5182623c48e685481107 (I can update `ember-awesome-macros` and it still works, only breaks after updating `ember-macro-helpers`.)

I can come up with a stripped down reproduction if this isn't helpful.

**Comment by kellyselden** [comment]
Thanks. A failing test PR would speed up the fixing process on my end

**Comment by DuBistKomisch** [comment]
Sure, I'll put one together today.

**Comment by DuBistKomisch** [comment]
Created a very simple demo in https://github.com/kellyselden/ember-macro-helpers/pull/160, took a while because I haven't written many tests for ember before, seems right though.

**Comment by mriska** [comment]
@kellyselden Have you had any time to reflect over how to resolve this and #176?

**Comment by kellyselden** [comment]
Should be fixed by https://github.com/kellyselden/ember-macro-helpers/pull/188, please confirm.

**Comment by DuBistKomisch** [comment]
:tada: I'll try it out this weekend.

**Comment by kellyselden** [comment]
Woohoo

**Comment by DuBistKomisch** [comment]
Seems to be working for me as well!
