### ISSUE TITLE
Lazy Computed with get/set

### ISSUE THREAD

**Issue by Techn1x** [kellyselden/ember-macro-helpers#209]
I'm trying to make a computed that will accept 2 values - a property, and a defaultProperty. When you get the computed, if property is not null/undefined, it will return the property - otherwise defaultProperty. However I also want to allow set on this computed, if set it will set the property to the set value.

```javascript
alarmState: defaultGet('reportConfig.alarm_state', raw([1,2,3]) ),
something2: defaultGet('reportConfig.show_state','showState'),
something3: defaultGet(conditional('something2','something2','alarmState'), raw('abc') ) // Allowing this would be nice too, but not required
```

So far I have
```
export default function(property, defaultProperty) {
  return lazyComputed(property, defaultProperty, {
    get(get, property, defaultProperty) {
      return isNone(get(property)) ? get(defaultProperty) : get(property);
    },
    set(newValue, get, property, defaultProperty) {
    // ???
    }
  });
}
```

I think I've done the get correctly (??) but I am a bit confused as to what to do in the set, can anyone help me out? Is what I'm trying to do even possible?

I've tried looking at examples at ember-awesome-macros and in this project, but none seem to do what I'm trying to do.

Thanks.

**Comment by Techn1x** [comment]
Ended up with this. It seems to work mostly but doesn't accept a curried computed object as the first arg.

```javascript
export default function(property, defaultProperty) {
  return lazyComputed(property, defaultProperty, {
    get(get, property, defaultProperty) {
      return isNone(get(property)) ? get(defaultProperty) : get(property);
    },
    set(newValue, get, property, defaultProperty) {
      trySet(property.context,property.macro,newValue);
    }
  });
}
```

Happy for this issue to be closed but would appreciate any input, even if it's "You done good". This macro helper stuff breaks my mind a bit.

**Comment by kellyselden** [comment]
I've released a new version (fixed a bug), and added a test resembling your situation. https://github.com/kellyselden/ember-macro-helpers/blob/master/tests/integration/lazy-curried-computed-test.js

The setter wasn't needed in this case. Let me know if this helps.

**Comment by Techn1x** [comment]
Realised I was running 0.17.0 of this addon so I've updated to 2.0.1 to be sure that's not the issue.

I switched to lazyCurriedComputed like you suggested, and removed the setter, this is what it looked like;
```javascript
// app/macros/default-get.js
import lazyCurriedComputed from 'ember-macro-helpers/lazy-curried-computed';

export default function(property, defaultProperty) {
  // return lazyComputed(property, defaultProperty, {
  return lazyCurriedComputed({
    get(get, property, defaultProperty) {
      return get(property) || get(defaultProperty);
    }
    // set(newValue, get, property, defaultProperty) {
    //	  trySet(property.context, property.macro, newValue);
    // }
  });
}
```

Elsewhere I have this defined;
`localSortArray: defaultGet('reportModel.sortLocal',raw([{tyre_position:'asc'}])),`

Unfortunately then if I do `this.get('localSortArray')` it returns a function, rather than a value

I'm a bit confused 😕

**Comment by Techn1x** [comment]
Also tried with lazyComputed, but without setter. It returns the correct value when you get it, but without the setter, when you set it the given property isn't updated

**Comment by kellyselden** [comment]
the curried computeds don't need that first line wrapper function. Try `export default lazyCurriedComputed(...`.

**Comment by Techn1x** [comment]
Ah ok. I've set it up like that now, and now lazyComputed and lazyCurriedComputed function similarly. Here's what I've got

```javascript
export default lazyCurriedComputed({
  get(get, property, defaultProperty) {
    return get(property) || get(defaultProperty);
  },
  //set(newValue, get, property, defaultProperty) {
  //  trySet(property.context, property.macro, newValue);
  //}
});
```

 - they just won't set without a setter defined. Or more specifically, the computed will be set, but the actual value behind the key used by the computed doesn't get set.

I guess in terms of the tests you linked above, what I am after is this;
```javascript
test('it sets the first key value', function(assert) {
  let { subject } = compute({
    computed: computed('key1', 'key2'),
    properties: {
      key1: null,
      key2: 2
    }
  });

  subject.set('computed', 3);

  assert.equal(subject.get('computed'), 3);
  // Extra tests
  assert.equal(subject.get('key1'),3);
  assert.equal(subject.get('key2'),2);
});
```

Note the extra asserts at the end. Sorry about any confusion, I hope this test ^^ clears up what I am trying to achieve. I think the lazyCurriedComputed code I linked seems like the best way to do it

**Comment by Techn1x** [comment]
Might be good to have an example of lazyCurriedComputed in the Readme

**Comment by kellyselden** [comment]
You will need to define your setter in this case to set the first key.
