### ISSUE TITLE
Broken in IE11 as of version 4.1.0

### ISSUE THREAD

**Issue by jon-hall** [kellyselden/ember-macro-helpers#271]
The addition of https://github.com/kellyselden/ember-macro-helpers/blob/v4.1.0/vendor/monkey-patch-ember-computed.js in version `4.1.0` seems to be breaking this addon in IE11 due to that file containing ES6 code that isn't being compiled by `ember-cli-babel`.

If required I can setup a reproduction repo to demonstrate the issue, but here are the basic steps to verify the problem:
- Create a new ember app with `ember-cli` (I used `ember-cli@3.11.0`): `ember new my-app`
- Update the `config/targets.js` file to include IE11 by default:
```
diff --git a/config/targets.js b/config/targets.js
index 8ffae36..03c1395 100644
--- a/config/targets.js
+++ b/config/targets.js
@@ -3,16 +3,10 @@
 const browsers = [
   'last 1 Chrome versions',
   'last 1 Firefox versions',
-  'last 1 Safari versions'
+  'last 1 Safari versions',
+  'ie 11'
 ];

-const isCI = !!process.env.CI;
-const isProduction = process.env.EMBER_ENV === 'production';
-
-if (isCI || isProduction) {
-  browsers.push('ie 11');
-}
-
```
- Add `ember-macro-helpers`: `ember install ember-macro-helpers`
- Serve the app and try viewing in IE11: `ember serve`
- A syntax error is shown in console for the monkey patch file

It'd be great if this addon could continue to support IE11, but if not then the incompatibility should probably be added to the README to let people know that the latest version doesn't support IE.

**Comment by kellyselden** [comment]
Do you know which line it fails on?

**Comment by jon-hall** [comment]
Thanks for the fast response, the first fail is on the arrow function (line 4), but I'd imagine it'll also fail on the spread operators (lines 12 and 23) once that's fixed, and also on the shorthand object syntax (lines 16 and 27) - from what I could see that's all that's in there that IE11 doesn't natively support.

**Comment by kellyselden** [comment]
Thanks. I'll get working on that.
