### ISSUE TITLE
-computed-store monkey patch breaks embroider build

### ISSUE THREAD

**Issue by scottkidder** [kellyselden/ember-macro-helpers#279]
Leaving this here in case anyone else runs into this. I think Embroider should have a solution.

https://github.com/embroider-build/embroider/issues/285

**Comment by kellyselden** [comment]
I'm open to other solutions. I couldn't think of a better way to do it to maintain backwards compatibility with latest versions of Ember.
Since this isn't really a bug here, I'm going to close for now. Thanks for tracking it though.
