### ISSUE TITLE
Consider exporting a collected object

### ISSUE THREAD

**Issue by mriska** [kellyselden/ember-macro-helpers#56]
In the same way that we can use:

```javascript
import nameOfMacro from 'ember-awesome-macros/name-of-macro';
// or
import { nameOfMacro } from 'ember-awesome-macros';
```
 in ember-awesome-macros, do you think it would be possible to support:

```javascript
import { raw } from 'ember-macro-helpers'
```

in ember-macro-helpers?

**Comment by kellyselden** [comment]
I would support a PR for this. I was trying to avoid a future rollup problem, but it looks like it won't be an issue https://github.com/emberjs/rfcs/pull/176#discussion_r92955863.

I will probably get to it if no one takes it on.

**Comment by mriska** [comment]
I can give it go. I'll see if I can find time for it during the weekend.
