### ISSUE TITLE
Upgrading ember-awesome-macros from 0.31.3 to 0.33.0 results in error when importing `ember-weakmap`

### ISSUE THREAD

**Issue by gabrielgrant** [kellyselden/ember-macro-helpers#71]
Worked with `ember-awesome-macros` 0.31.3. After upgrade to 0.33.0 I'm getting an error from `ember-macro-helpers`:

```
Error while processing route: app.repos.repo.index Could not find module `ember-weakmap` imported from `ember-macro-helpers/create-class-computed` Error: Could not find module `ember-weakmap` imported from `ember-macro-helpers/create-class-computed`
```
Strangely, `npm ls` shows  `ember-weakmap@2.0.0` installed:

```
...
├─┬ ember-awesome-macros@0.33.0
│ ├─┬ broccoli-file-creator@1.1.1
│ │ ├─┬ broccoli-kitchen-sink-helpers@0.2.9
│ │ │ └── glob@5.0.15
│ │ └── rsvp@3.0.21
│ ├─┬ broccoli-merge-trees@2.0.0
│ │ └── merge-trees@1.0.1
│ ├── ember-cli-string-utils@1.1.0
│ ├─┬ ember-macro-helpers@0.12.0
│ │ └── ember-weakmap@2.0.0
│ └── ember-string-ishtmlsafe-polyfill@1.1.0
...
```

**Comment by kellyselden** [comment]
I haven't seen this in any of my projects using it. Can you give any more info? node, os, npm, yarn versions? Did you try wiping node_modules? Do you have anything npm linked?

**Comment by gabrielgrant** [comment]
Thanks for the follow-up. I had tried blowing away node_modules, but I think something may have been screwy with my NPM cache -- blowing away node_modules again, as well as bower pkgs, and both their caches (as well as updating to the latest ember-cli) seemed to fix the issue.
