### ISSUE TITLE
Readme documentation for `createClassComputed` seems to be erroneous

### ISSUE THREAD

**Issue by lolmaus** [kellyselden/ember-macro-helpers#84]
Hey.

Tried to understand the usage example of `createClassComputed` in the readme and it made no sense to me.

[Actual](https://github.com/kellyselden/ember-awesome-macros/blob/master/addon/array/filter-by.js) usage example does make sense and is different from the readme:

1. The second-argument-callback receives all arguments and not only the ones marked as true like readme claims.
2. The CP returned from the callback uses dynamic values as dependencies while readme uses hardcoded strings `"array"` and `"value"`.

Not sending a PR because I'm not fully confident in my understanding of `createClassComputed`.

**Comment by kellyselden** [comment]
You are very right. The docs were missing some incoming params. Thanks for finding and reporting this!
