### ISSUE TITLE
Changelog please

### ISSUE THREAD

**Issue by lolmaus** [kellyselden/ember-macro-helpers#92]
Updated from `0.5.0` to `0.14.0` and my project broke. Figured I had to update `ember-awesome-macros` as well, but having a list of breaking changes would be nice.

**Comment by kellyselden** [comment]
Added a generated changelog in https://github.com/kellyselden/ember-macro-helpers/commit/b4f2a35e3dfdc8168c0c789f9ae2fa48d7324d4a

Hopefully that helps!

**Comment by lolmaus** [comment]
Are you gonna update it manually from now on? :innocent:
